// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	util "github.com/0chain/common/core/util"
	mock "github.com/stretchr/testify/mock"
)

// MPTIteratorHandler is an autogenerated mock type for the MPTIteratorHandler type
type MPTIteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, path, key, node
func (_m *MPTIteratorHandler) Execute(ctx context.Context, path util.Path, key util.Key, node util.Node) error {
	ret := _m.Called(ctx, path, key, node)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Path, util.Key, util.Node) error); ok {
		r0 = rf(ctx, path, key, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMPTIteratorHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMPTIteratorHandler creates a new instance of MPTIteratorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMPTIteratorHandler(t mockConstructorTestingTNewMPTIteratorHandler) *MPTIteratorHandler {
	mock := &MPTIteratorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
