// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MPTSerializableSize is an autogenerated mock type for the MPTSerializableSize type
type MPTSerializableSize struct {
	mock.Mock
}

// MarshalMsg provides a mock function with given fields: _a0
func (_m *MPTSerializableSize) MarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Msgsize provides a mock function with given fields:
func (_m *MPTSerializableSize) Msgsize() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UnmarshalMsg provides a mock function with given fields: _a0
func (_m *MPTSerializableSize) UnmarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMPTSerializableSize interface {
	mock.TestingT
	Cleanup(func())
}

// NewMPTSerializableSize creates a new instance of MPTSerializableSize. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMPTSerializableSize(t mockConstructorTestingTNewMPTSerializableSize) *MPTSerializableSize {
	mock := &MPTSerializableSize{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
