// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MPTSerializable is an autogenerated mock type for the MPTSerializable type
type MPTSerializable struct {
	mock.Mock
}

// MarshalMsg provides a mock function with given fields: _a0
func (_m *MPTSerializable) MarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnmarshalMsg provides a mock function with given fields: _a0
func (_m *MPTSerializable) UnmarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMPTSerializable interface {
	mock.TestingT
	Cleanup(func())
}

// NewMPTSerializable creates a new instance of MPTSerializable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMPTSerializable(t mockConstructorTestingTNewMPTSerializable) *MPTSerializable {
	mock := &MPTSerializable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
