// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	util "github.com/0chain/common/core/util"
	mock "github.com/stretchr/testify/mock"
)

// MPTMissingNodeHandler is an autogenerated mock type for the MPTMissingNodeHandler type
type MPTMissingNodeHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, path, key
func (_m *MPTMissingNodeHandler) Execute(ctx context.Context, path util.Path, key util.Key) error {
	ret := _m.Called(ctx, path, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Path, util.Key) error); ok {
		r0 = rf(ctx, path, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMPTMissingNodeHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMPTMissingNodeHandler creates a new instance of MPTMissingNodeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMPTMissingNodeHandler(t mockConstructorTestingTNewMPTMissingNodeHandler) *MPTMissingNodeHandler {
	mock := &MPTMissingNodeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
