// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	util "github.com/0chain/common/core/util"
	mock "github.com/stretchr/testify/mock"
)

// NodeDBIteratorHandler is an autogenerated mock type for the NodeDBIteratorHandler type
type NodeDBIteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, key, node
func (_m *NodeDBIteratorHandler) Execute(ctx context.Context, key util.Key, node util.Node) error {
	ret := _m.Called(ctx, key, node)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Key, util.Node) error); ok {
		r0 = rf(ctx, key, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNodeDBIteratorHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodeDBIteratorHandler creates a new instance of NodeDBIteratorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodeDBIteratorHandler(t mockConstructorTestingTNewNodeDBIteratorHandler) *NodeDBIteratorHandler {
	mock := &NodeDBIteratorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
