// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecureSerializableValueI is an autogenerated mock type for the SecureSerializableValueI type
type SecureSerializableValueI struct {
	mock.Mock
}

// GetHash provides a mock function with given fields:
func (_m *SecureSerializableValueI) GetHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHashBytes provides a mock function with given fields:
func (_m *SecureSerializableValueI) GetHashBytes() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MarshalMsg provides a mock function with given fields: _a0
func (_m *SecureSerializableValueI) MarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnmarshalMsg provides a mock function with given fields: _a0
func (_m *SecureSerializableValueI) UnmarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSecureSerializableValueI interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecureSerializableValueI creates a new instance of SecureSerializableValueI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecureSerializableValueI(t mockConstructorTestingTNewSecureSerializableValueI) *SecureSerializableValueI {
	mock := &SecureSerializableValueI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
