// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Serializable is an autogenerated mock type for the Serializable type
type Serializable struct {
	mock.Mock
}

// Decode provides a mock function with given fields: _a0
func (_m *Serializable) Decode(_a0 []byte) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encode provides a mock function with given fields:
func (_m *Serializable) Encode() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

type mockConstructorTestingTNewSerializable interface {
	mock.TestingT
	Cleanup(func())
}

// NewSerializable creates a new instance of Serializable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSerializable(t mockConstructorTestingTNewSerializable) *Serializable {
	mock := &Serializable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
